### ISSUE TITLE
lit to add

### ISSUE THREAD

**Issue by Tyhcass** [fsolt/dcpo_trust_bureaucracy#2]
Koumpias, A. M., Leonardo, G., & Martinez-Vazquez, J. (2020). Trust in government institutions and tax morale. " “More importantly, our findings show that it is trust in output government organizations that implement and deliver public goods and services to the citizenry that has a significantly larger impact on tax morale as compared to citizens’ trust in input-side organizations, such as the legislative and the executive branches of the government that design policy” ([Koumpias et al., 2020, p. 5])"

**Comment by fsolt** [comment]
https://www.tandfonline.com/doi/abs/10.1080/01900692.2016.1156696

**Comment by fsolt** [comment]
Steven Van de Walle & Koen Migchelbrink (2022) Institutional quality, corruption, and impartiality: the role of process and outcome for citizen trust in public administration in 173 European regions, Journal of Economic Policy Reform, 25:1, 9-27, DOI: [10.1080/17487870.2020.1719103](https://doi.org/10.1080/17487870.2020.1719103)

https://www.tandfonline.com/doi/full/10.1080/17487870.2020.1719103?casa_token=l_IkH11It5MAAAAA%3AekMdqOq6_645dpx2ZdWRlyc7SiiFucO0a9UR-Jp-lKstFOGzoLsN3vGfki_AcZ3XRQEL5gpndIWT

**Comment by fsolt** [comment]
Nurgul R. Aitalieva (2018) Bureaucracy and Public Trust. In Ali Farazmand (Ed.), Global Encyclopedia of Public Administration, Public Policy, and Governance. Springer.
doi: 10.1007/978-3-319-31816-5_633-1

https://link.springer.com/referenceworkentry/10.1007/978-3-319-31816-5_633-1
https://www.researchgate.net/profile/Nurgul-Aitalieva/publication/322098551_Bureaucracy_and_Public_Trust/links/5a7e6126aca272a73765d33a/Bureaucracy-and-Public-Trust.pdf

**Comment by fsolt** [comment]
David J. Houston & Lauren Howard Harding (2013) Public Trust in Government Administrators, Public Integrity, 16:1, 53-76, DOI: [10.2753/PIN1099-9922160103](https://doi.org/10.2753/PIN1099-9922160103)

https://www.tandfonline.com/action/showCitFormats?doi=10.2753%2FPIN1099-9922160103
